---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-alerts
  namespace: monitoring
spec:
  encryptedData:
    feishu_webhook_url: AgDXNH8e0IKAO1mqwfMZ+gfsAiduXD5VhUNtpg+XFZCXdCSgX67juNaVzL7IQkR5FE8mCUdtG1DfyXoVG6h+OUptMeNOj5iI/BRf4VfikvB5HgUdpKKB6y+0AfGmYHynWwGgvehk/Oyzg4IDrMAq7obHhztyBI7uKc/UcU9FjdqoBtPSYqxC/+e3v17YDY+Lt8T3yAAbvoWnfG4/o3cxNFyKxffJMAHfvxZAKKS9Tutkx53PfINEMYwT4Liv2DtUTUfQc2C4VzDg8gTwmNerPHzglBVByCOlYjAY9B0fv2NhxBgUomgyE6nBO/FtrZQItLBizhNbo6gLXtHRQyfOJm8vDO0Q4qw/QBJdhGMSB6+xIEXjGWizmdziiTMyo87yYiwD2A0A+JLTJh2vyi/H7Ou3h5Gsf0iXvKVS7DgKzkM4CxfqzXYfbDrDJF0CfK2R1F1GV4STgXM0FI/mP5nDkUVjfae9Df+4AzHtPS9ZOOPv93KF0t1HbRrOBg/6VbbFv4KwFwCZVT4syzykihTzfz/za8wbaVZoVuL60TNRKvQGwkaICTK9fke0OZeDW46XUwdqVyCsQEDqePeAo87jGnC3gCUl40ZFoB9M1raJ8dfsB5my6QludFlf1Qd5rurH9PjuC503kKflN9L2ArNJOTr3NnvlTJj/6i2A0FEsSCdF0mqVSKyEdADNoHYDC6+TJ4ITWXbIj1vC0wLRLMT5lqTJ9IjvwXuJXKimmiiYu3yJewpAfAWy11yY/cumK1fQT3XloAFnaPniwmWytKjg/rVGm0gYj5vNJLGVqh/R4Lxst1I=
    grafana_admin_password: AgATEb1b2V1+71eRCvXkmu6GJvZ00C1VHHvfCmiWOgvgFH1TZnGKKr6hk3smYIxuAVjn4mTODe6zVUioHGFz97F/+jyALzcp4kYaCgZjp5JUW9f3hkjGcyFCkKVk1PrT8VN40RzT5gDuuIkP3Rqikm9/PvXuz3KUEmpnb9BUT2TLQKtOiMBKRO/3n7d9GMunm0eJZ0hi2hKpT9WX+S/zRY2Q1QqePuG8K4t2/o2NeXrK/WADybIqbuaefmbu52aH73eMISHnRPds1dgTTfqSvvHI4TRpfBLf+VQvI3c4A4yyKD6ZB5CDncR5wVTdj6aNN+2h6rTlkJEk2ZnOe0GWQW65TJBepguu/xx2i2YQiQ3WUV4bTnrMqEQSDFGCjm/lmdcHkEuCEh/FQqZLlgCBJTLY1tSV4m5r56l/YuspXczccfQXh+NW/01aWy5Nyg/JBjD1gCtmsaFje5h/fjYpQea0MO/BPzqcHBDQSl0hRf9Q+FqqDeakxPRoemgu/b6GL4gia0EOeLM4vj+sjG2ww/FMUyKSNSNtyCgYFrgQlYcGdGz20rbDIKHeQlTQ9wJl41f0ZE4CIOh3Y8GhhcEoHK7HDCtU5X853/+qK4VQDLr8s2NHFATjR1/Y7Tfp2FbT2pYk3mYgyxhEyauf02tC65WTgBFSBS0zc/OJH/FAWEcJbGeOtdcJ22qOeQgoa7vVwGV9U21/lISy56HyKAM3HlG1ooo5BfW5+s0=
  template:
    metadata:
      name: monitoring-alerts
      namespace: monitoring
    type: Opaque
